### PR TITLE
[WIP] Use lazy initialisation for ResolvedDependencyGraph class

### PR DESCRIPTION
**Pull request by wongzigii**
Use lazy initialisation for ResolvedDependencyGraph class

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Thanks for the pull request!

Ideally, this lazy initialization could be completely opaque to the callers, though. One possible way we could do this is by implementing a custom `CollectionType` which lazily provides its elements. What do you think about that idea?

**Comment by wongzigii** [comment]
Sounds interesting! The first glance in my mind was an ordered array like this: `[Depth0<Depth0Count: Int>, Depth1<Depth1Count: Int>, Depth2<Depth2Count: Int>...]`. Am I heading in the right direction?

**Comment by wongzigii** [comment]
Sounds interesting! The first glance in my mind was an ordered array like: `[DepthOfGraph0, DepthOfGraph1, DepthOfGraph2 ...]`.

**Comment by jspahrsummers** [comment]
Yep, that should work. ☺️

**Comment by wongzigii** [comment]
Just implemented a CollectionType from my point of view. And seems like that I could not generate such an array in specific order. Advices are very appreciated !

**Comment by jspahrsummers** [comment]
I was thinking we would use a custom `CollectionType` for _each_ of the lists of depth-ordered dependencies. In other words, there would be a collection for depth index 0, a different collection for depth index 1, etc.

This is a good start, though. Let me know if you'd like me to take it over and implement what I've described here. 😄

**Comment by wongzigii** [comment]
Hmm, feel free to close  or merge this pull request if need. Sorry for misunderstanding. Will keep watching and learning. :D

**Comment by jspahrsummers** [comment]
Thanks for getting this started! I committed something slightly different in f659630051b5db2c1f26b0d6a70b720855a7d191, but it's a very similar idea, and I'm glad you took a stab at it. 🙇

**Pull request closed without merging**
