### PR TITLE
Allow requirements to carry a priority

### PR DESCRIPTION
**Pull request by jspahrsummers**
Priority is used to determine which requirements are eligible for intersection. Requirements in two different priority bands will never be intersected.

This can be used to implement unpinned versions like a branch or commit hash, by creating a requirement which is higher priority (a lower numeric index) than the default.

cc @mdiep

### CODE REVIEW

**Comment by mdiep** [comment]
I think there are 3 scenarios worth considering:

## Scenario 1

* Project A is used by 3 different projects
* Project 1 uses A ~> 1.0
* Project 2 uses an unversioned release by A
* Project 3 uses A ~> 2.0

Will resolving 1, 2, and 3 fail because 1 and 3 are incompatible?

## Scenario 2

* Project A is used by 3 different projects
* Project 1 uses A ~> 1.0
* Project 2 uses an unversioned release by A
* Project 3 uses a different unversioned release by A?

Will resolving 1, 2, and 3 fail because 2 and 3 are incompatible?

## Scenario 3

* Project A is used by 3 different projects
* Project 1 uses A ~> 1.0
* Project 2 uses an unversioned release by A
* Project 3 uses A ~> 1.1

Will resolving 1, 2, and 3 succeed?

**Comment by jspahrsummers** [comment]
The answer to all of these—at least with this PR—is, "it depends on the requirements' priorities." All of the scenarios given _can_ succeed if the unversioned requirement which should "win" is given the highest priority.

**Comment by mdiep** [comment]
👍🏻

If it were me, I'd make version handling less generic and implement a specific scheme. But if you want Arbiter to be more generic, this makes sense.

**Comment by jspahrsummers** [comment]
This seemed like a good compromise between being too general and being too coupled to what we specifically did in Carthage. For one example, I think Arbiter should be able to support local-only dependency resolution where semantic versions don't really exist at all.

**Pull request merged**
