### PR TITLE
Expose full resolved graph information in public API, split "depths" logic into Installer type

### PR DESCRIPTION
**Pull request by jspahrsummers**
#45 and #46 will be easier if users are able to _reconstitute_ a fully resolved dependency graph and pass it _into_ Arbiter, instead of just consuming them. To do that, we basically move all of the `DependencyGraph` API which was only in `Resolver.cpp` into the public interface, and move the previous "install-ordered graph" logic into a more properly named `ArbiterResolvedDependencyInstaller` type.

**To do:**

 - [x] Update bindings

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Before I refactor the Swift bindings to match, how does this API feel?

cc @mdiep

**Comment by mdiep** [comment]
Makes sense.

It might be worth considering a `OrderedResolvedDependencyGraph` that stores the nodes in a specified order—without tying it to the install order specifically. That will mess up the phase stuff. But  Carthage plans to sort `Cartfile.resolved` in lexicographical order to reduce conflicts.

Also, ordering the unresolved graph can be useful to direct the search and prevent backtracking. I'm not sure whether you're sharing any code between resolved and un-resolved graphs, but if you are that might be a win.

**Comment by jspahrsummers** [comment]
`ArbiterResolvedDependencyGraph` offers nodes in project identifier order already. Is that kind of what you mean, or do you mean being able to use arbitrary ordering functions?

The install-ordered thing seems very unique, in that it's not just a sort function, but incorporates notions of "can be installed concurrently" as well. I'm not sure that sort of paradigm applies to other orderings.

**Comment by mdiep** [comment]
> Is that kind of what you mean, or do you mean being able to use arbitrary ordering functions?

I meant arbitrary.

> The install-ordered thing seems very unique, in that it's not just a sort function, but incorporates notions of "can be installed concurrently" as well. I'm not sure that sort of paradigm applies to other orderings.

Yup. So it's totally based on whatever direction you want to take it.

**Comment by jspahrsummers** [comment]
@mdiep I'm not sure I understand what sort of API you'd be interested in. Would you be interested in opening a PR to discuss the interface changes?

**Comment by mdiep** [comment]
I don't think it matters from an end-user perspective. I've just learned that ordering the nodes can be helpful in preventing backtracking when you're resolving the graph. ([_Constraint Processing_ by Rina Dechter](https://www.amazon.com/gp/product/1558608907/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1558608907&linkCode=as2&tag=mattdiephouse-20&linkId=1c958d2684749921ee5fba75c45c49a7), chapter 4)

**Pull request merged**
